// <auto-generated />
using System;
using Folha01.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Folha01.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Folha01.Models.BeneficiosModel", b =>
                {
                    b.Property<int>("IdBeneficios")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdBeneficios ");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBeneficios"), 1L, 1);

                    b.Property<string>("HorasExtras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HorasExtras");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionario");

                    b.Property<string>("Recisaofuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Recisaofuncionario");

                    b.Property<double>("Va")
                        .HasColumnType("float")
                        .HasColumnName("VA");

                    b.Property<double>("Vt")
                        .HasColumnType("float")
                        .HasColumnName("VT");

                    b.HasKey("IdBeneficios");

                    b.ToTable("Beneficios");
                });

            modelBuilder.Entity("Folha01.Models.CadastroFModel", b =>
                {
                    b.Property<int>("IdFuncionario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFuncionario"), 1L, 1);

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatadeNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Perfil")
                        .HasColumnType("int");

                    b.Property<string>("SenhaFuncionario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdFuncionario");

                    b.ToTable("FuncionarioCadastro");
                });

            modelBuilder.Entity("Folha01.Models.CargoModel", b =>
                {
                    b.Property<int>("IdCargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCadastro");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCargo"), 1L, 1);

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Função");

                    b.HasKey("IdCargo");

                    b.ToTable("Funcionario Cargo");
                });

            modelBuilder.Entity("Folha01.Models.ContratoModel", b =>
                {
                    b.Property<int>("IdContrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdContrato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdContrato"), 1L, 1);

                    b.HasKey("IdContrato");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Folha01.Models.FrequenciaModel", b =>
                {
                    b.Property<int>("IdFrequencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdFrequencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFrequencia"), 1L, 1);

                    b.Property<double>("Data")
                        .HasColumnType("float")
                        .HasColumnName("Data");

                    b.Property<int>("Faltas")
                        .HasColumnType("int")
                        .HasColumnName("Faltas");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionario");

                    b.HasKey("IdFrequencia");

                    b.ToTable("Frequencia");
                });

            modelBuilder.Entity("Folha01.Models.HoleriteModel", b =>
                {
                    b.Property<int>("IDHolerite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDHolerite");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDHolerite"), 1L, 1);

                    b.Property<int>("Contrato")
                        .HasColumnType("int")
                        .HasColumnName("IdContrato");

                    b.Property<DateTime>("DataAdmissao")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Admissao");

                    b.Property<DateTime>("DataAtual")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data_Atual");

                    b.Property<int>("IdBeneficios")
                        .HasColumnType("int")
                        .HasColumnName("IdBeneficios");

                    b.Property<int>("IdFrequencia")
                        .HasColumnType("int")
                        .HasColumnName("IdFrequencia");

                    b.Property<int>("IdFuncionario")
                        .HasColumnType("int")
                        .HasColumnName("IdFuncionario");

                    b.Property<double>("SalarioBase")
                        .HasColumnType("float")
                        .HasColumnName("SalarioBase");

                    b.Property<double>("SalarioLiquido")
                        .HasColumnType("float")
                        .HasColumnName("SalarioLiquido");

                    b.HasKey("IDHolerite");

                    b.ToTable("Holerite");
                });

            modelBuilder.Entity("Folha01.Models.LoginModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LoginF");
                });
#pragma warning restore 612, 618
        }
    }
}
